<?php
$tool_name = "ChatGPT Detector";
$tool_slug = "chatgpt-detector";
$tool_description = "Identify if text was generated by ChatGPT or similar AI models.";
$system_prompt = "You are an expert at detecting ChatGPT-generated content. Analyze the text for patterns typical of ChatGPT output. Provide a confidence score (0-100%) and explain your reasoning. Output only the analysis result.";
$input_label = "Enter text to check:";
$button_text = "Check for ChatGPT";
$placeholder = "Paste text to detect ChatGPT usage...";
include __DIR__ . '/includes/tool-template.php';
